### ISSUE TITLE
Integration in Clippy ?

### ISSUE THREAD

**Issue by Urgau** [BurtonQin/lockbud#14]
Great work, I'm wondering if it could be directly integrated into clippy.

Do you think it would be possible ?
If yes, does it sound reasonable to have it as a general mechanism, for example having `#[clippy::forbid_call(self, ::crate::module::my_fn)]` at the function definition ?

**Comment by BurtonQin** [comment]
It's hard because lockbud works on MIR while clippy on HIR. lockbud triggers a `cargo build` underneath and I do not think clippy should go so deep.
But I do believe that adding warning lints for the following cases may help:
```
// locks called in conditionals of `match` or `if let`
match *a.read().data {
   Some(_) => { ... }
    _ => handle(*a.read().data2),
}
```
and
```
struct Foo {
   data: RwLock<i32>
}
// may deadlock when a and b point to the same Foo.
fn cmp(a: &Foo, b: &Foo) -> bool {
   a.data.read() == b.data.read()
}
```

**Comment by BurtonQin** [comment]
Recursive read locks does not mean recursive functions, instead, it means that a lock is called twice, and the first one is not unlocked when the second one is called.
