### ISSUE TITLE
why use the "instance" rather than implementing a block visitor to build the callgraph?

### ISSUE THREAD

**Issue by ffanyq** [BurtonQin/lockbud#42]

**Comment by BurtonQin** [comment]
The implementation uses `Instance::resolve` to get the callee instance.
https://github.com/BurtonQin/lockbud/blob/69e139995ea2fdbd0c25c389c753a66cf6e208ad/src/analysis/callgraph/mod.rs#L211

An instance is more suitable than a function's `def_id` in the analysis in that 
i) the instance here is fully instantiated, providing concrete type info and handy APIs.
and ii) eliminating dead functions.

**Comment by ffanyq** [comment]
Thanks for your answer!
