### ISSUE TITLE
run ./detect.sh failed

### ISSUE THREAD

**Issue by wasd96040501** [BurtonQin/lockbud#44]
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/luoyangze.ptrl/rust/lockbud/target/debug/lockbud rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 127)
  --- stderr
  /home/luoyangze.ptrl/rust/lockbud/target/debug/lockbud: error while loading shared libraries: librustc_driver-281a9b3e4c740b61.so: cannot open shared object file: No such file or directory

**Comment by BurtonQin** [comment]
Note that you must use the same rustc nightly version as lockbud to detect your project.
