### ISSUE TITLE
FP Panic Warning

### ISSUE THREAD

**Issue by stoneman258** [BurtonQin/lockbud#62]
## Description
I encountered an FP `panic warning when using `lockbud` in my crate. The minmized code example is listed below. It seems lockbud adopts regular expression to recognize panic, which can easily lead to false positives (e.g., [Link](https://github.com/dtolnay/no-panic/blob/f19bd8cf373752a5cdaf820d38fb9ab5932c07dd/src/lib.rs#L150)). 

## Case
```rust
fn main() {
    to_panic_report();
}
fn to_panic_report() {
    println!("...");
    // ...
}
```
## Command

```bash
cargo lockbud -k panic
```

## Result

```bash
PANIC[testa#0]: (DefId(0:3 ~ testa[3645]::main), bb0[0]): span[src/main.rs:2:5: 2:22 (#0)], outermost_span[src/main.rs:1:1: 3:2 (#0)], Panic(Instance { def: Item(DefId(0:4 ~ testa[3645]::to_panic_report)), args: [] })
testa: Panic: 1
```
Lockbud report a wrong `panic` warning.

**Comment by BurtonQin** [comment]
Thanks I will fix it ASAP.
